// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgrrcqutztwizcnssrpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncnJjcXV0enR3aXpjbnNzcnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTcyNjksImV4cCI6MjA2ODk5MzI2OX0.EDQidsg5umZ0WGznBr0U4RPZfxNznQVi68hBvDFp1Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});